// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoHKNyuEHOI_PIRyHYxedV-aAPpCRI17o',
    appId: '1:1016767921919:web:6dec630e26ee35d3d356ca',
    messagingSenderId: '1016767921919',
    projectId: 'tc3-flutter-app',
    authDomain: 'tc3-flutter-app.firebaseapp.com',
    storageBucket: 'tc3-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFMMGyD1lTyMFwrhcf1K27OqKPbtUuovA',
    appId: '1:1016767921919:android:612b338c111e9dc6d356ca',
    messagingSenderId: '1016767921919',
    projectId: 'tc3-flutter-app',
    storageBucket: 'tc3-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqiEPbbEJvPuNjTqi5APgOEtmLLOrtvjo',
    appId: '1:1016767921919:ios:2a07e9b281ffa73ed356ca',
    messagingSenderId: '1016767921919',
    projectId: 'tc3-flutter-app',
    storageBucket: 'tc3-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqiEPbbEJvPuNjTqi5APgOEtmLLOrtvjo',
    appId: '1:1016767921919:ios:2a07e9b281ffa73ed356ca',
    messagingSenderId: '1016767921919',
    projectId: 'tc3-flutter-app',
    storageBucket: 'tc3-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoHKNyuEHOI_PIRyHYxedV-aAPpCRI17o',
    appId: '1:1016767921919:web:409b55c82f0da878d356ca',
    messagingSenderId: '1016767921919',
    projectId: 'tc3-flutter-app',
    authDomain: 'tc3-flutter-app.firebaseapp.com',
    storageBucket: 'tc3-flutter-app.firebasestorage.app',
  );
}
